#!/usr/bin/env bash
# This script displays a list of currently running processes

# Display header with fixed width
printf "%-14s %-14s %-14s %-s\n" "PID" "PPID" "USER" "COMMAND"

# Display processes with hierarchy
ps axo pid,ppid,user,comm --forest

