#!/usr/bin/env bash
# This script displays a list of currently running processes

# Display header
echo "PID   PPID  USER     COMMAND"

# Display processes with hierarchy
ps axo pid,ppid,user,comm --forest

