#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles signals

# Function to handle SIGTERM signal
terminate_process() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 1
}

# Function to handle SIGINT signal
interrupt_process() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit_process() {
    echo "Y U no love me?!"
    rm /var/run/myscript.pid
    exit 1
}

# Trap signals
trap 'terminate_process' SIGTERM
trap 'interrupt_process' SIGINT
trap 'quit_process' SIGQUIT

# Save PID to file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

