#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the process ID of 4-to_infinity_and_beyond
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v "grep" | awk '{print $2}')

# Check if the process ID is not empty
if [ -n "$pid" ]; then
    # Send SIGINT signal to the process
    kill -2 "$pid"
    echo "Process terminated"
else
    echo "Process not found"
fi

