#!/usr/bin/env bash
# This script configures an Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add or update hostname mappings in /etc/hosts
sudo sed -i '/^127.0.0.1[[:space:]]localhost$/s/$/ 127.0.0.2/' /etc/hosts
sudo sed -i '/^::1[[:space:]]localhost$/s/$/ 127.0.0.2/' /etc/hosts
sudo sed -i '$ a 8.8.8.8 facebook.com' /etc/hosts

