#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on, including localhost IP.

# It then use the ip command to get a list of all network interfaces and their associated IP addresses
# Filter out only IPv4 addresses and print them
ip -o -4 addr show scope global | awk '{print $4}' | cut -d'/' -f1

