# Ensure ~/.ssh directory exists
file { '/root/.ssh':
  ensure => 'directory',
  owner  => 'root',
  group  => 'root',
  mode   => '0700',
}

# Ensure ~/.ssh/config file exists with correct permissions and content
file { '/root/.ssh/config':
  ensure  => 'file',
  owner   => 'root',
  group   => 'root',
  mode    => '0600',
  content => "
    # SSH client configuration generated by Puppet

    # Use specific private key
    IdentityFile ~/.ssh/school

    # Disable password authentication
    PasswordAuthentication no

    # Other SSH configurations can be added here if needed
  ",
}

